openapi: 3.0.0
info: { title: form-networking, version: 1.0.0 }
paths:
  /health:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
  /api/applications:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
