openapi: 3.0.0
info: { title: form-networking, version: 1.0.0 }
paths:
  /health:
    get:
      responses:
        '200':
          description: Health check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  message:
                    type: string
                    description: Human-readable health status.
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
  /:
    get:
      responses:
        '200':
          description: Static client shell
          content:
            text/html:
              schema:
                type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
    head:
      responses:
        '200':
          description: Static client headers
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
  /index.html:
    get:
      responses:
        '200':
          description: Static client shell
          content:
            text/html:
              schema:
                type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
    head:
      responses:
        '200':
          description: Static client headers
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
  /app.js:
    get:
      responses:
        '200':
          description: Static application script
          content:
            application/javascript:
              schema:
                type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
    head:
      responses:
        '200':
          description: Static application script headers
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
  /app.css:
    get:
      responses:
        '200':
          description: Static application styles
          content:
            text/css:
              schema:
                type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
    head:
      responses:
        '200':
          description: Static application styles headers
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
  /api/applications:
    get:
      responses:
        '200':
          description: Masked application list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                    name_mask:
                      type: string
                    user_mask:
                      type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
    post:
      responses:
        '200':
          description: Submission accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '400':
          description: Invalid submission payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Missing or invalid authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
    options:
      responses:
        '204':
          description: CORS preflight
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${FUNCTION_ID}
        service_account_id: ${FUNCTION_INVOKER_SA_ID}
