name: CD - API Gateway

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # обязательно для OIDC

env:
  FOLDER_ID: b1gr0igqr38nt8rm70li
  SA_ID: ajepvcf5o5fl77h8b2cf
  GATEWAY_NAME: form-networking-gw
  OPENAPI_TEMPLATE: apigateway/openapi.yaml
  OPENAPI_FILE: apigateway/openapi.resolved.yaml
  FUNCTION_NAME: ${{ vars.YC_FUNCTION_NAME || 'form-networking' }}
  FUNCTION_ID: ${{ vars.YC_FUNCTION_ID || '' }}
  FUNCTION_INVOKER_SA_ID: ${{ vars.YC_FUNCTION_INVOKER_SA_ID || '' }}

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Acquire IAM token
        if: ${{ env.FUNCTION_ID == '' }}
        id: iam-token
        uses: yc-actions/yc-iam-token-fed@1.0.0
        with:
          yc-sa-id: ${{ env.SA_ID }}

      - name: Resolve Cloud Function ID
        if: ${{ env.FUNCTION_ID == '' }}
        env:
          IAM_TOKEN: ${{ steps.iam-token.outputs.token }}
          FOLDER_ID: ${{ env.FOLDER_ID }}
          FUNCTION_NAME: ${{ env.FUNCTION_NAME }}
        run: |
          set -euo pipefail
          if [[ -z "${IAM_TOKEN}" ]]; then
            echo "Failed to obtain IAM token via workload identity" >&2
            exit 1
          fi
          if [[ -z "${FUNCTION_NAME}" ]]; then
            echo "FUNCTION_NAME is not configured; set the YC_FUNCTION_NAME repository variable." >&2
            exit 1
          fi
          echo "Resolving Cloud Function ID for '${FUNCTION_NAME}' in folder ${FOLDER_ID}"
          filter=$(printf "name = '%s'" "${FUNCTION_NAME}")
          payload=$(jq -n --arg folder "${FOLDER_ID}" --arg filter "${filter}" '{folderId: $folder, filter: $filter}')
          response=$(curl --fail --silent --show-error \
            -H "Authorization: Bearer ${IAM_TOKEN}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "${payload}" \
            "https://serverless-functions.api.cloud.yandex.net/functions/v1/functions:list")
          function_id=$(printf '%s' "${response}" | jq -r '.functions[0].id // empty')
          if [[ -z "${function_id}" ]]; then
            echo "Failed to resolve Cloud Function ID; ensure '${FUNCTION_NAME}' exists in folder ${FOLDER_ID} or set the YC_FUNCTION_ID repository variable." >&2
            echo "API response: ${response}" >&2
            exit 1
          fi
          echo "Resolved Cloud Function ID: ${function_id}"
          {
            echo "FUNCTION_ID=${function_id}"
          } >> "${GITHUB_ENV}"

      # Если OpenAPI лежит в другом приватном репозитории — используй этот блок вместо верхнего
      # и добавь PAT (scope: repo) в секрет CI_REPO_TOKEN:
      # - name: Checkout external repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: AlAlNi/form-networking
      #     ref: main
      #     token: ${{ secrets.CI_REPO_TOKEN }}
      #     fetch-depth: 1

      - name: Sanity checks
        run: |
          set -euo pipefail
          echo "FOLDER_ID=${FOLDER_ID}"
          echo "SA_ID=${SA_ID}"
          echo "GATEWAY_NAME=${GATEWAY_NAME}"
          echo "OPENAPI_TEMPLATE=${OPENAPI_TEMPLATE}"
          echo "OPENAPI_FILE=${OPENAPI_FILE}"
          echo "FUNCTION_NAME=${FUNCTION_NAME}"
          if [[ -z "${FUNCTION_ID}" ]]; then
            echo "FUNCTION_ID is not configured; set the YC_FUNCTION_ID repository variable or ensure the Cloud Function exists." >&2
            exit 1
          fi
          ls -la "$(dirname "${OPENAPI_TEMPLATE}")" || true
          test -f "${OPENAPI_TEMPLATE}" || { echo "OpenAPI template not found: ${OPENAPI_TEMPLATE}" >&2; exit 1; }

      - name: Render API Gateway specification
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "${OPENAPI_FILE}")"
          node infra/render-apigw.mjs "${OPENAPI_TEMPLATE}" "${OPENAPI_FILE}" --function-id "${FUNCTION_ID}"

      - name: Validate OpenAPI specification
        run: |
          set -euo pipefail
          npx --yes @redocly/cli@latest lint "${OPENAPI_FILE}"

      - name: Deploy API Gateway
        uses: yc-actions/yc-api-gateway-deploy@v3.0.0
        with:
          yc-sa-id: ${{ env.SA_ID }}
          folder-id: ${{ env.FOLDER_ID }}
          gateway-name: ${{ env.GATEWAY_NAME }}
          spec-file: ${{ env.OPENAPI_FILE }}

      - name: Done
        run: echo "API Gateway ${GATEWAY_NAME} deployed"
