name: CD - API Gateway

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read        # чтобы checkout работал
  id-token: write       # обязательно для OIDC

env:
  FOLDER_ID: b1gr0igqr38nt8rm70li
  SA_ID: ajepvcf5o5fl77h8b2cf
  GATEWAY_NAME: form-networking-gw
  OPENAPI_FILE: apigateway/openapi.yaml

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Если openapi лежит в другом приватном репо — вместо блока выше используй этот,
      # и добавь PAT в секрет CI_REPO_TOKEN (scope: repo):
      # - name: Checkout external repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: AlAlNi/form-networking
      #     ref: main
      #     token: ${{ secrets.CI_REPO_TOKEN }}
      #     fetch-depth: 1

      - name: Sanity echo
        run: |
          echo "Folder: $FOLDER_ID"
          echo "SA:     $SA_ID"
          ls -la $(dirname "$OPENAPI_FILE") || true
          test -f "$OPENAPI_FILE" || { echo "OpenAPI not found at $OPENAPI_FILE"; exit 1; }

      - name: Deploy API Gateway
        uses: yc-actions/yc-api-gateway-deploy@v3.0.0
        with:
          yc-sa-id: ${{ env.SA_ID }}
          folder-id: ${{ env.FOLDER_ID }}
          gateway-name: ${{ env.GATEWAY_NAME }}
          openapi-spec: ${{ env.OPENAPI_FILE }}

      - name: Done
        run: echo "API Gateway $GATEWAY_NAME deployed"
