name: CT Deploy

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

env:
  YC_FOLDER_ID: ${{ vars.YC_FOLDER_ID }}
  YC_SA_ID: ${{ vars.YC_SA_ID_TEST || vars.YC_SA_ID_SHARED }}
  FUNCTION_NAME: ${{ vars.YC_FUNCTION_NAME_TEST || 'form-networking-test' }}
  FUNCTION_RUNTIME: ${{ vars.YC_FUNCTION_RUNTIME || 'nodejs22' }}
  FUNCTION_ENTRYPOINT: ${{ vars.YC_FUNCTION_ENTRYPOINT || 'index.handler' }}
  FUNCTION_MEMORY: ${{ vars.YC_FUNCTION_MEMORY_TEST || '256Mb' }}
  FUNCTION_SOURCEROOT: ${{ vars.YC_FUNCTION_SOURCEROOT || 'server/' }}

concurrency:
  group: test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Deploy test function
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate configuration
        shell: bash
        run: |
          set -euo pipefail
          missing=()
          [[ -n "${YC_FOLDER_ID:-}" ]] || missing+=("YC_FOLDER_ID")
          [[ -n "${YC_SA_ID:-}" ]] || missing+=("YC_SA_ID_TEST or YC_SA_ID_SHARED")
          [[ -n "${FUNCTION_NAME:-}" ]] || missing+=("YC_FUNCTION_NAME_TEST")
          if (( ${#missing[@]} )); then
            echo "::error::Missing required variables: ${missing[*]}"
            exit 1
          fi

      - name: Deploy Cloud Function
        id: deploy
        uses: yc-actions/yc-sls-function@v3.1.0
        with:
          yc-sa-id: ${{ env.YC_SA_ID }}
          folder-id: ${{ env.YC_FOLDER_ID }}
          function-name: ${{ env.FUNCTION_NAME }}
          runtime: ${{ env.FUNCTION_RUNTIME }}
          memory: ${{ env.FUNCTION_MEMORY }}
          entrypoint: ${{ env.FUNCTION_ENTRYPOINT }}
          source-root: ${{ env.FUNCTION_SOURCEROOT }}
          include: |
            **/*.json
            **/*.js
            **/*.html
            **/*.css

      - name: Publish deployment summary
        if: success()
        run: |
          {
            echo "### Test deployment"
            echo ""
            echo "- Function ID: \`${{ steps.deploy.outputs.function-id || 'n/a' }}\`"
            echo "- Function name: \`${FUNCTION_NAME}\`"
            echo "- Pull Request: #${{ github.event.pull_request.number }}"
          } >> "$GITHUB_STEP_SUMMARY"
