name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      YC_CLOUD_ID:  ${{ secrets.YC_CLOUD_ID }}
      WEB_BUCKET:   ${{ secrets.WEB_BUCKET }}
      S3_ENDPOINT:  ${{ secrets.S3_ENDPOINT }}
      BOT_TOKEN:    ${{ secrets.BOT_TOKEN }}
      APIGW_NAME:   ${{ secrets.APIGW_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # ---------- Install YC CLI (без внешних GitHub Actions) ----------
      - name: Install YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i $HOME/yandex-cloud -n
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
          $HOME/yandex-cloud/bin/yc version

      - name: YC auth
        env:
          YC_SA_JSON: ${{ secrets.YC_SA_JSON }}
        run: |
          echo "$YC_SA_JSON" > key.json
          yc config set service-account-key key.json
          yc config set folder-id $YC_FOLDER_ID
          yc config set cloud-id  $YC_CLOUD_ID
          yc config set endpoint api.cloud.yandex.net
          rm -f key.json

      # ---------- Backend: Function ----------
      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Zip server
        run: |
          cd server
          zip -r ../server.zip .

      - name: Ensure function exists
        id: fn
        run: |
          set -e
          FN_NAME="form-networking-fn"
          if yc serverless function get --name "$FN_NAME" >/dev/null 2>&1; then
            echo "exists=1" >> $GITHUB_OUTPUT
          else
            yc serverless function create --name "$FN_NAME"
            echo "exists=0" >> $GITHUB_OUTPUT
          fi
          FN_ID=$(yc serverless function get --name "$FN_NAME" --format json | jq -r .id)
          echo "id=$FN_ID" >> $GITHUB_OUTPUT

      - name: Deploy function version
        run: |
          yc serverless function version create \
            --function-id  ${{ steps.fn.outputs.id }} \
            --runtime nodejs18 \
            --entrypoint index.handler \
            --memory 128m \
            --execution-timeout 5s \
            --environment BOT_TOKEN=${BOT_TOKEN},DEMO=1 \
            --source-path server.zip

      # ---------- API Gateway ----------
      - name: Prepare OpenAPI with function id
        run: |
          cp infra/apigw-openapi.yaml apigw.yaml
          sed -i "s|\${FUNCTION_ID}|${{ steps.fn.outputs.id }}|g" apigw.yaml

      - name: Ensure API Gateway exists
        id: gw
        run: |
          set -e
          if yc serverless api-gateway get --name "$APIGW_NAME" >/dev/null 2>&1; then
            yc serverless api-gateway update --name "$APIGW_NAME" --spec=apigw.yaml
          else
            yc serverless api-gateway create --name "$APIGW_NAME" --spec=apigw.yaml
          fi
          GW_URL=$(yc serverless api-gateway get --name "$APIGW_NAME" --format json | jq -r .domain)
          echo "url=https://${GW_URL}" >> $GITHUB_OUTPUT

      # ---------- Frontend: inject API URL & upload ----------
      - name: Inject API base URL into web/app.js
        run: |
          API_BASE="${{ steps.gw.outputs.url }}"
          sed -i "s|%%API_BASE%%|$API_BASE|g" web/app.js

      - name: Install AWS CLI
        run: |
          pip install --upgrade --user awscli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure AWS credentials (Yandex S3)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: 'ru-central1'

      - name: Upload web to Object Storage
        run: |
          aws --endpoint-url ${S3_ENDPOINT} s3 sync ./web s3://${WEB_BUCKET} --delete

      - name: Summary
        run: |
          {
            echo "Frontend URL: https://storage.yandexcloud.net/${WEB_BUCKET}/index.html"
            echo "API Base URL : ${{ steps.gw.outputs.url }}"
          } | tee -a "$GITHUB_STEP_SUMMARY"
