name: Deploy to Yandex Cloud
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      YC_CLOUD_ID:  ${{ secrets.YC_CLOUD_ID }}
      WEB_BUCKET:   ${{ secrets.WEB_BUCKET }}
      S3_ENDPOINT:  ${{ secrets.S3_ENDPOINT }}
      BOT_TOKEN:    ${{ secrets.BOT_TOKEN }}
      APIGW_NAME:   ${{ secrets.APIGW_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets (fail fast)
        run: |
          test -n "${{ secrets.YC_SA_JSON }}" || (echo "YC_SA_JSON is empty" && exit 1)
          test -n "${YC_FOLDER_ID}"           || (echo "YC_FOLDER_ID is empty" && exit 1)
          test -n "${YC_CLOUD_ID}"            || (echo "YC_CLOUD_ID is empty" && exit 1)
          test -n "${APIGW_NAME}"             || (echo "APIGW_NAME is empty" && exit 1)
          test -n "${WEB_BUCKET}"             || (echo "WEB_BUCKET is empty" && exit 1)
          test -n "${{ secrets.S3_ACCESS_KEY_ID }}"     || (echo "S3_ACCESS_KEY_ID is empty" && exit 1)
          test -n "${{ secrets.S3_SECRET_ACCESS_KEY }}" || (echo "S3_SECRET_ACCESS_KEY is empty" && exit 1)

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i $HOME/yandex-cloud -n
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
          yc version

      - name: YC auth
        env:
          YC_SA_JSON: ${{ secrets.YC_SA_JSON }}
        run: |
          echo "$YC_SA_JSON" > key.json
          yc config set service-account-key key.json
          yc config set cloud-id  "$YC_CLOUD_ID"
          yc config set folder-id "$YC_FOLDER_ID"
          yc config set endpoint api.cloud.yandex.net

      # ---------- Backend ----------
      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Zip server
        run: |
          cd server
          zip -r ../server.zip .

      - name: Ensure function exists
        id: fn
        run: |
          set -e
          FN_NAME="form-networking-fn"
          if yc serverless function get --name "$FN_NAME" --folder-id "$YC_FOLDER_ID" >/dev/null 2>&1; then
            echo "exists=1" >> $GITHUB_OUTPUT
          else
            yc serverless function create --name "$FN_NAME" --folder-id "$YC_FOLDER_ID"
            echo "exists=0" >> $GITHUB_OUTPUT
          fi
          FN_ID=$(yc serverless function get --name "$FN_NAME" --folder-id "$YC_FOLDER_ID" --format json | jq -r .id)
          echo "id=$FN_ID" >> $GITHUB_OUTPUT
          echo "FN_ID=$FN_ID"

      - name: Deploy function version
        run: |
          yc serverless function version create \
            --function-id  "${{ steps.fn.outputs.id }}" \
            --runtime nodejs18 \
            --entrypoint index.handler \
            --memory 128m \
            --execution-timeout 5s \
            --environment BOT_TOKEN=${BOT_TOKEN},DEMO=1 \
            --source-path server.zip

      - name: Wait function ACTIVE
        run: |
          for i in {1..40}; do
            st=$(yc serverless function version list --function-id "${{ steps.fn.outputs.id }}" --folder-id "$YC_FOLDER_ID" --format json | jq -r '.[-1].status')
            [ "$st" = "ACTIVE" ] && exit 0
            sleep 3
          done
          echo "Function version not ACTIVE"; exit 1

      # ---------- API Gateway ----------
      - name: Prepare OpenAPI with function id
        run: |
          cp infra/apigw-openapi.yaml apigw.yaml
          sed -i "s|\${FUNCTION_ID}|${{ steps.fn.outputs.id }}|g" apigw.yaml
          echo "== apigw.yaml ==" && cat apigw.yaml

      - name: Resolve SA_ID (no jq on bindings)
        id: sa
        run: |
          set -e
          SA_NAME="form-networking-sa"
          yc iam service-account get --name "$SA_NAME" --format json > sa.json
          SA_ID=$(jq -r '.id' sa.json)
          if [ -z "$SA_ID" ] || [ "$SA_ID" = "null" ]; then
            echo "Failed to resolve SA_ID"; cat sa.json; exit 1
          fi
          echo "id=$SA_ID" >> $GITHUB_OUTPUT
          echo "SA_ID=$SA_ID"

      - name: Ensure API Gateway exists (idempotent, with SA)
        id: gw
        env:
          APIGW_NAME: ${{ secrets.APIGW_NAME }}
        run: |
          set -e
          if yc serverless api-gateway get --name "$APIGW_NAME" --folder-id "$YC_FOLDER_ID" >/dev/null 2>&1; then
            echo "Updating API GW: $APIGW_NAME"
            for i in 1 2 3 4 5; do
              yc --debug serverless api-gateway update \
                --name "$APIGW_NAME" \
                --folder-id "$YC_FOLDER_ID" \
                --service-account-id "${{ steps.sa.outputs.id }}" \
                --spec=apigw.yaml && break
              sleep $((i*3))
            done
          else
            echo "Creating API GW: $APIGW_NAME"
            for i in 1 2 3 4 5; do
              yc --debug serverless api-gateway create \
                --name "$APIGW_NAME" \
                --folder-id "$YC_FOLDER_ID" \
                --service-account-id "${{ steps.sa.outputs.id }}" \
                --spec=apigw.yaml && break
              sleep $((i*3))
            done
          fi
          GW_URL=$(yc serverless api-gateway get --name "$APIGW_NAME" --folder-id "$YC_FOLDER_ID" --format json | jq -r .domain)
          echo "url=https://${GW_URL}" >> $GITHUB_OUTPUT
          echo "GW_URL=https://${GW_URL}"

      # ---------- Frontend ----------
      - name: Inject API base URL into web/app.js
        run: |
          API_BASE="${{ steps.gw.outputs.url }}"
          sed -i "s|%%API_BASE%%|$API_BASE|g" web/app.js
          echo "API_BASE set to $API_BASE"

      - name: Install AWS CLI
        run: |
          pip install --upgrade --user awscli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure AWS credentials (Yandex S3)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: 'ru-central1'

      - name: Upload web to Object Storage
        run: |
          aws --endpoint-url "${S3_ENDPOINT}" s3 sync ./web s3://${WEB_BUCKET} --delete

      - name: Summary
        run: |
          echo "Frontend URL: https://storage.yandexcloud.net/${WEB_BUCKET}/index.html"
          echo "API Base URL : ${{ steps.gw.outputs.url }}"

      - name: Upload YC trace logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: yc-traces
          path: /home/runner/.config/yandex-cloud/logs/*.txt
